"""Ports declared by the core (Cockburn's hexagon): what the graph and the tools need from the outside.

`RunStore` is the run-scoped State; `Index` is the code index (symbols, definitions, call graph).

`Index` is language-agnostic. Adapters live in scanner/adapter/index: one LSP-backed adapter per
language (Go, Python, TypeScript, JavaScript), a grep fallback, and a multiplexer that picks the
adapter by file extension. Symbols are addressed by fully-qualified-ish names as agents write them:
"pingHandler", "Server.login", "(*Server).login", "s.login", "pkg.Func" — adapters normalise.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict

from scanner.core.types import Anchor, Dossier, Finding, Hypothesis


class Symbol(BaseModel):
    """One definition: 1-based lines; `line` is the selection (name) line, `end_line` closes the body."""

    model_config = ConfigDict(extra="ignore")
    name: str
    kind: str = ""  # function | method | class | struct | variable | ...
    file: str  # relative to the target root
    line: int
    end_line: int = 0
    container: str = ""  # enclosing class/struct/receiver, if any


@runtime_checkable
class Index(Protocol):
    """The code index: symbols and definitions, references and the call graph, reachability — LSP per language with
    a grep fallback (adapter.index); `close()` stops the language servers. An LSP adapter also exposes `failed`
    (it gave up: missing server, protocol error) so the fallback can take over."""

    def find_symbol(self, fqn: str) -> tuple[str, int] | None: ...
    def has_symbol(self, fqn: str) -> bool: ...
    def symbols(self, file: str) -> list[Symbol]: ...
    def definition_range(self, fqn: str) -> tuple[str, int, int] | None: ...
    def references(self, fqn: str) -> list[tuple[str, int, str]]: ...
    def callers(self, fqn: str) -> list[tuple[str, int, str]]: ...
    def callees(self, fqn: str) -> list[tuple[str, int, str]]: ...
    def path_to_entry(self, fqn: str, entries: list[str], max_depth: int = 6) -> list[str] | None: ...
    def close(self) -> None: ...


@runtime_checkable
class RunStore(Protocol):
    """Run-scoped State as the graph and the tools use it (scanner.adapter.store.Run implements it)."""

    def anchors(self) -> list[Anchor]: ...
    def anchor(self, anchor_id: str) -> Anchor | None: ...
    def save_anchors(self, anchors: list[Anchor]) -> None: ...
    def put_hypotheses(self, rnd: int, hs: list[Hypothesis]) -> None: ...
    def put_dossiers(self, rnd: int, ds: list[Dossier]) -> None: ...
    def findings(self) -> list[Finding]: ...
    def report(self, f: Finding) -> Finding: ...
    def set_status(self, finding_id: str, status: str, evidence: list[str], note: str = "") -> Finding | None: ...
    def annotate(self, finding_id: str, **fields) -> Finding | None:
        """Merge report-only annotations (review) into a finding.
        Raises ValueError for verdict fields (status, evidence, confidence, id, anchor_id): those belong to the gates."""
    def log_gate(self, anchor_id: str, reason: str) -> None: ...
    def add_note(self, text: str, ref: str = "") -> None: ...
    def notes(self) -> list[dict]: ...
    def put_artifact(self, stage: str, obj: dict) -> None: ...
    def artifact(self, stage: str) -> dict | None: ...
